### ISSUE TITLE
Suggestions: Add support for glowing item frames & add support for the unbreaking enchantment (1-3)

### ISSUE THREAD

**Issue by ghost** [Mrflaxe/InvisibleFrames#1]
Hey there! I have taken a look at yoir plugin and I really like the idea of making itemframes invisible using shears, but I have a few suggestions to round up the experience a little:

First of all, I would like to see support for glowing item frames as well as normal item frames.

Second, it would be awesome to have a chance of not reducing the durability of the shears if the unbreaking enchantment is applied to the shears.

Feel free to respond :D

**Comment by Mrflaxe** [comment]
Thanks for your suggestions.
Yeah, about unbreaking enchantment I forgot, but I'll correct this in next release.
About glowing item frames... I have some technical limitations that do not allow me to run versions higher than 1.16. So I can try add glowing item frames support, but can't test it for correct work by myself.

**Comment by ghost** [comment]
Awesome, and thanks for your reply mate!
Feel free to hit me with it, I can test the update if its ready and let you know :D

**Comment by Mrflaxe** [comment]
Well, look at the latest release and let me know if something doesn't work. Hope it will don't.

**Comment by ghost** [comment]
Yes Sir, awesome! Both new additions seem to be working perfectly fine, durability reduction works fine, even depending on the level, also glowing item frames seem to turn invisble exactly as expected!

Well done, and thanks a lot!

**Comment by ghost** [comment]
Any chance your have a donation link, paypal, or similar?

**Comment by Mrflaxe** [comment]
> Any chance your have a donation link, paypal, or similar?

Here: [removed link]

**Comment by ghost** [comment]
Hm sadly it does not seem to work, im getting an error from paypal, something like "The owner does only allow payments using his website". Maybe you can have a look at this!

**Comment by Mrflaxe** [comment]
It's weird. Try this one: https://www.paypal.com/donate/?hosted_button_id=7MPBKHPGMMJJG

**Comment by ghost** [comment]
Same error

**Comment by Mrflaxe** [comment]
It's really sad. I think this happens because of sanctions for my country. This is first time I've getting donation, so maybe you can suggest other ways to get donation?

**Comment by ghost** [comment]
If you're willing to you can try to give me your paypal email and I send it manually :D

**Comment by Mrflaxe** [comment]
Okay, here: [deleted]

**Comment by ghost** [comment]
Its the same error, it seems if this is a bussiness account there is a option somewhere that prevents users from sending money to it, maybe you can check your account settings, otherwise it really might be because of the reason you just named... which would be pretty crap

**Comment by Mrflaxe** [comment]
I can't find any setting or option that can fix our problem. I don't know what to do with that

**Comment by ghost** [comment]
Hm sorry mate, I never experienced this issue before. Anyways thank you again for your help on this and keep up the awesome work! I'm sorry that I'm not able to send you a tip, there is just something off with paypal i guess..
